### ISSUE TITLE
Can I please get some more details on how to test the setup? 

### ISSUE THREAD

**Issue by shah-hussain-khattak** [OpenSIPS/opensips-ai-voice-connector-ce#1]
Hi, 

First, thanks for taking the initiative to launch this project, it is amazing! 

I cloned the repository, configured the API keys in the .env variables file, and spun up the containers, but now I don't know how to test it. I tried to send a call with openai in the To header, but it failed:

```
Oct 31 00:48:49 [21] WARNING:core:fm_malloc: not enough contiguous free pkg memory (14362328 bytes left, need 18446744073351778744), attempting defragmentation... please increase the "-M" command line parameter!
Oct 31 00:48:49 [21] ERROR:core:fm_malloc: not enough free pkg memory (14362328 bytes left, need 18446744073351778744), please increase the "-M" command line parameter!
Oct 31 00:48:49 [21] ERROR:core:payload_add_params: Failed to create JSON string reason
Oct 31 00:48:49 [21] ERROR:core:evi_build_payload: Failed to add parameters
Oct 31 00:48:49 [21] ERROR:event_datagram:datagram_raise: Failed to build event payload E_UA_SESSION
Oct 31 00:48:49 [21] ERROR:b2b_entities:raise_ua_sess_event: cannot raise event
Oct 31 00:48:49 [21] ERROR:b2b_entities:b2b_ua_server_init: Failed to raise E_UA_SESSION event
Oct 31 00:48:49 [21] NOTICE:Started new call for B2B.42.465.1730335728.1752196206
Oct 31 00:49:00 [51] WARNING:core:handle_timer_job: utimer job <tm-utimer> has a 20000 us delay in execution: trigger_time=103270000 ijiffies=103290000 ijiffies_extra=0
```

Can you please share some guidance, how to test this setup and what is the right way to configure different API interfaces and test it? 

Regards, 
Shah Hussain

**Comment by razvancrainea** [comment]
Hi, Hussain!

Your steps seem to be correct, but it looks like the latest opensips docker image was pointing to a bad version. I've just pushed the latest tag upstream. Make sure you pull it by running `docker pull opensips/opensips:latest`, then retry.
Regarding a guide, this would indeed be helpful. I will keep this ticket open until one is available. Thanks for the suggestion!

Best regards,
Răzvan

**Comment by dariusstefan** [comment]
Hello, Hussain!

We just released a more [detailed guide](https://github.com/OpenSIPS/opensips-ai-voice-connector-ce/blob/main/docs/getting-started.md), which I hope will be more helpful. Thanks for the suggestion!

Best regards,
Darius!

**Comment by shah-hussain-khattak** [comment]
Thank you guys for the prompt response! I have progressed a little bit, having one problem, and will create a separate issue for it.
